
export const MONTH_THEMES = [
  { color: 'text-slate-500', icon: 'fa-brain', pt: 'Janeiro Branco (Saúde Mental)', en: 'White January (Mental Health)' },
  { color: 'text-purple-600', icon: 'fa-clover', pt: 'Fevereiro Roxo (Lúpus e Alzheimer)', en: 'Purple February (Lupus & Alzheimer)' },
  { color: 'text-blue-900', icon: 'fa-dna', pt: 'Março Azul Marinho (Câncer Colorretal)', en: 'Navy Blue March (Colorectal Cancer)' },
  { color: 'text-blue-400', icon: 'fa-puzzle-piece', pt: 'Abril Azul (Autismo)', en: 'Blue April (Autism Awareness)' },
  { color: 'text-amber-500', icon: 'fa-traffic-light', pt: 'Maio Amarelo (Prevenção de Acidentes)', en: 'Yellow May (Traffic Safety)' },
  { color: 'text-red-600', icon: 'fa-droplet', pt: 'Junho Vermelho (Doação de Sangue)', en: 'Red June (Blood Donation)' },
  { color: 'text-yellow-500', icon: 'fa-shield-virus', pt: 'Julho Amarelo (Hepatites Virais)', en: 'Yellow July (Viral Hepatitis)' },
  { color: 'text-amber-600', icon: 'fa-baby', pt: 'Agosto Dourado (Aleitamento Materno)', en: 'Golden August (Breastfeeding)' },
  { color: 'text-yellow-600', icon: 'fa-ribbon', pt: 'Setembro Amarelo (Prevenção ao Suicídio)', en: 'Yellow September (Suicide Prevention)' },
  { color: 'text-pink-500', icon: 'fa-person-breastfeeding', pt: 'Outubro Rosa (Câncer de Mama)', en: 'Pink October (Breast Cancer)' },
  { color: 'text-blue-600', icon: 'fa-mars', pt: 'Novembro Azul (Câncer de Próstata)', en: 'Blue November (Prostate Cancer)' },
  { color: 'text-red-500', icon: 'fa-heart-circle-check', pt: 'Dezembro Vermelho (AIDS)', en: 'Red December (AIDS Awareness)' },
];

export const TRANSLATIONS = {
  pt: {
    appName: "Assistente",
    navCalendar: "Calendário",
    navAgenda: "Agenda",
    navResearch: "Pesquisa",
    navChat: "Chat",
    navHealth: "Saúde",
    navActivity: "Atividade",
    searchPlaceholder: "Pesquise com IA...",
    chatPlaceholder: "Envie uma mensagem...",
    addEvent: "Novo Evento",
    noEvents: "Sem compromissos.",
    title: "Título",
    description: "Descrição",
    date: "Data",
    save: "Salvar",
    cancel: "Cancelar",
    delete: "Excluir",
    history: "Histórico",
    sources: "Fontes:",
    logAction: "Ação",
    logDetails: "Detalhes",
    logTime: "Hora",
    aiThinking: "IA processando...",
    welcome: "Bem-vindo",
    selectDay: "Selecione um dia.",
    tasks: "Tarefas",
    events: "Eventos",
    notes: "Notas",
    lightStatus: "Luzes",
    lightOn: "Ligadas",
    lightOff: "Desligadas",
    healthTitle: "Resumo de Saúde",
    addExercise: "Treino",
    exerciseName: "Atividade",
    duration: "Tempo (min)",
    intensity: "Nível",
    low: "Leve",
    medium: "Médio",
    high: "Intenso",
    generateWorkout: "Gerar Treino",
    recentExercises: "Atividades",
    recoveryTab: "Superação",
    daysClean: "Dias Limpos",
    moneySaved: "Economizado",
    dailyCost: "Gasto Diário (Antigo)",
    startDate: "Data de Início",
    savingChart: "Economia Acumulada",
    setupRecovery: "Configurar Jornada",
    offModeTitle: "Modo Off",
    offModeMsg: "Sempre aqui por você.",
    importTraining: "Importar (Print/QR)",
    importing: "Analisando imagem...",
    importSuccess: "Treino importado com sucesso!",
    importError: "Erro ao ler a imagem.",
    dailyRecipe: "Sugestão Saudável do Dia",
    generateRecipe: "Gerar Receita",
    recipeLoading: "Cozinhando ideias...",
    recipeInstruction: "Ingredientes e Preparo"
  },
  en: {
    appName: "Assistant",
    navCalendar: "Calendar",
    navAgenda: "Agenda",
    navResearch: "Search",
    navChat: "Chat",
    navHealth: "Health",
    navActivity: "Activity",
    searchPlaceholder: "Search with AI...",
    chatPlaceholder: "Send a message...",
    addEvent: "New Event",
    noEvents: "No events.",
    title: "Title",
    description: "Description",
    date: "Date",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    history: "History",
    sources: "Sources:",
    logAction: "Action",
    logDetails: "Details",
    logTime: "Time",
    aiThinking: "AI thinking...",
    welcome: "Welcome",
    selectDay: "Select a day.",
    tasks: "Tasks",
    events: "Events",
    notes: "Notes",
    lightStatus: "Lights",
    lightOn: "On",
    lightOff: "Off",
    healthTitle: "Health Resume",
    addExercise: "Workout",
    exerciseName: "Activity",
    duration: "Time (min)",
    intensity: "Level",
    low: "Low",
    medium: "Mid",
    high: "High",
    generateWorkout: "New Workout",
    recentExercises: "Activities",
    recoveryTab: "Recovery",
    daysClean: "Clean Days",
    moneySaved: "Money Saved",
    dailyCost: "Old Daily Cost",
    startDate: "Start Date",
    savingChart: "Accumulated Savings",
    setupRecovery: "Setup Journey",
    offModeTitle: "Off Mode",
    offModeMsg: "Always here for you.",
    importTraining: "Import (Print/QR)",
    importing: "Analyzing image...",
    importSuccess: "Training imported successfully!",
    importError: "Error reading image.",
    dailyRecipe: "Daily Healthy Suggestion",
    generateRecipe: "Generate Recipe",
    recipeLoading: "Cooking ideas...",
    recipeInstruction: "Ingredients & Steps"
  }
};
